version: '3.8'

services:
  # Основной интерфейс Streamlit и ядро парсера
  app:
    build: .
    container_name: ai_miner_bot
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    restart: unless-stopped

  # Телеграм-бот (работает параллельно)
  tg_bot:
    build: .
    container_name: mining_tg_bot
    # Запускаем именно файл бота
    command: python tg_bot.py
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    restart: unless-stopped
    depends_on:
      - app